#!/bin/sh
# This file is a part of the ipfs-daemon-initd project, and is licensed under 
# the MIT license
# Copyright 2015 Jeff Cochran
#
### BEGIN INIT INFO
# Provides:          ipfs-daemon 
# Required-Start:    $remote_fs $network $named $syslog
# Required-Stop:     $remote_fs $network $named $syslog
# Should-Start:      iptables ip6tables firewalld
# Should-Stop:       $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop IPFS Daemon
# Description:       Starts or stops the IPFS Daemon with watchdogging
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
DESC="Interplanetary File System (IPFS)"
NAME=ipfsd
DAEMON=/usr/local/bin/ipfs
DAEMON_NAME=ipfs
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/${NAME}.log
SCRIPTNAME=/etc/init.d/"$NAME"
DAEMON_UID=ipfsd
DAEMON_OPTIONS="--mount"

which $DAEMON || exit 0

. /lib/lsb/init-functions

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

do_start()
{
        # Return
        #   0 if daemon has been started
        #   1 if daemon was already running
        #   other if daemon could not be started or a failure occured
	start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --chuid $DAEMON_UID --background --output $LOGFILE --exec ${DAEMON} daemon -- $DAEMON_OPTIONS
}

do_stop()
{
        # Return
        #   0 if daemon has been stopped
        #   1 if daemon was already stopped
        #   other if daemon could not be stopped or a failure occurred
        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON

case "$1" in
start)  
        log_daemon_msg "Starting ${DESC}: $DAEMON_NAME"
        do_start
        case "$?" in
                0) log_end_msg 0 ;;
                1) log_progress_msg "already started"
                   log_end_msg 0 ;;
                *) log_end_msg 1 ;;
        esac
        ;;
stop)   
        log_daemon_msg "Stopping ${DESC}:  $DAEMON_NAME"
        do_stop
        case "$?" in
                0) log_end_msg 0 ;;
                1) log_progress_msg "already stopped"
                   log_end_msg 0 ;;
                *) log_end_msg 1 ;;
        esac
        ;;
restart)
        log_daemon_msg "Restarting ${DESC}: $DAEMON_NAME" 
        $0 stop
        $0 start
        ;;
reload|force-reload)
        log_daemon_msg "Reloading ${DESC}: $DAEMON_NAME"
        # cron reloads automatically
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON_NAME $NAME && exit 0 || exit $?
        ;;
*)      log_action_msg "Usage: /etc/init.d/$NAME {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0
